name: Build Android AAB

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system packages
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip python3-setuptools python3-wheel zip openjdk-17-jdk

      - name: Install buildozer
        run: pip install buildozer

      - name: Install Cython
        run: pip install Cython

      - name: Install Kivy
        run: pip install kivy

      - name: Build AAB
        run: buildozer android release

      - name: Upload AAB artifact (v4)
        uses: actions/upload-artifact@v4
        with:
          name: android-aab
          path: bin/*.aab
