name: Build AAB

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip python3-setuptools \
                              git zip unzip openjdk-17-jdk

      - name: Install buildozer
        run: |
          pip install --upgrade cython
          pip install buildozer

      - name: Install p4a
        run: pip install python-for-android

      - name: Check buildozer.spec
        run: cat buildozer.spec

      - name: Build AAB
        run: buildozer -v android release

      - name: Upload AAB artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-aab
          path: bin/*.aab
